import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from '@styles/pages/Layout.module.scss';
import "@/styles/globals.scss";
import Header from "@components/Header/Header";
import HeaderWrapper from "@components/HeaderWrapper/HeaderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeaderWrapper/>
        <main>
          <div className={styles.container}>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
